### ISSUE TITLE
utils.dataset.SPCUP22DatasetDownloader gives error in os.remove()

### ISSUE THREAD

**Issue by rafathasan** [AGenCyLab/SPCUP2022#8]
This error raise when SPCUP22DatasetDownloader is used with different config file instead of "dataset.yaml". It seems like it is a File deadlock problem.

## Here is my config "mel_feature.yaml"

```
spcup22:
  mel_feature:
      training:
         link: https://www.dropbox.com/s/9nkc8eyu5lfendp/spcup_2022_training.zip?dl=1
         filename: spcup_2022_training.zip
         default_path: data/spcup22/mal_feature/training
      evaluation_part1:
         link: https://www.dropbox.com/s/d1kob8d11ynrv8m/spcup_2022_eval_part1_mel_features.zip?dl=1
         filename: spcup_2022_eval_part1_mel_features.zip
         default_path: data/spcup22/mal_feature/evaluation_part1
```

## Error:
 
![image](https://user-images.githubusercontent.com/33374525/158907944-dd71035d-90a3-4631-a9b0-2186b1800ad7.png)
